#! /bin/bash
# Update MicroPython source and prepare for build

cd $MPDIR
echo Working...
git checkout master
git pull origin master --tags
git submodule sync
git submodule update --init
cd mpy-cross
make clean
make -j 8
cd ../ports/stm32
make BOARD=PYBV11 clean
make BOARD=PYBV10 clean
make BOARD=PYBLITEV10 clean
make BOARD=PYBD_SF2 clean
make BOARD=PYBD_SF3 clean
make BOARD=PYBD_SF6 clean
cd ../esp8266
make clean
cd ../unix
make clean
make submodules
make -j 8
